### PR TITLE
Loosen Rails requirement to allow usage with Rails 5

### PR DESCRIPTION
**Pull request by louim**
There you go!

### CODE REVIEW

**Comment by nimashariatian** [comment]
can we merge this?

**Comment by cllns** [comment]
@nimashariatian All set and released as `0.0.6`. :) 
**Please** let  me know if you have any problems. I haven't had a chance to test this engine with Rails 5.

**Comment by nimashariatian** [comment]
@cllns thank you!! :) will report back if anything went wrong, also will attempt to create fixes and make a PR if needed

**Comment by cllns** [comment]
you're a hero! 👍

**Pull request merged**
